# thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
    check-template-location: true
    cache: false
    servlet:
      content-type: text/html
  mvc:
    throw-exception-if-no-handler-found: true