
code-generator:
  # mysql connection
  db:
    driverClass: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.198.29:3306/db_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    userName: root
    password: MysqL@951QwdC
  # code gen pack
  generate:
    outputBase:  # 放空该项则代码生成到当前项目中
    packBase: com.lwl.base.code.gen
    packBean: pojo
    packApi: api
    packController: controller
    packService: service
    packDao: dao
    packMapper: mapper
    packWeb: com.lwl.web
  copyright:
    author: LinWenLi
    version: 1.0